# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  bicepfile: '**/main.bicep'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'sc-azure-dumoulin'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az deployment group create --resource-group rg-dumoulin --template-file $(bicepfile) --parameters location=CanadaCentral dbPassword="Bonjour123"'