parameters:
   environment: ''
   artifactName: ''
   serviceConnection: ''
   webAppName: ''

jobs:
- deployment : 'WebDeploy'
  pool:
    vmImage: 'ubuntu-latest'
  environment: '${{ parameters.environment }}'
  strategy:
     runOnce:
       deploy:
         steps:
             - task: DownloadBuildArtifacts@1
               inputs:
                 buildType: 'current'
                 downloadType: 'single'
                 artifactName: '${{ parameters.artifactName }}'
                 downloadPath: '$(System.ArtifactsDirectory)'
             - task: AzureRmWebAppDeployment@4
               displayName: 'Déployer dans App Service'
               inputs:
                ConnectionType: 'AzureRM'
                azureSubscription: '${{ parameters.serviceConnection }}'
                appType: 'webApp'
                appName: '${{ parameters.webAppName }}'
                WebAppName: '${{ parameters.webAppName }}'
                package: '$(System.ArtifactsDirectory)/**/*.zip'